version: "3.8"
services:
  nginx_flask:
    image: yubin0611/nginx_flask:python2
    container_name: nginx_iis
    ports:
      - "80:80"
    volumes:
      - /tmp:/tmp
      # mount flask project to /uwsgi/project
      # - /home/yubin/project/coral_pdltte:/uwsgi/project/coral_pdltte
      # mount global static to /uwsgi/static
      # - /home/yubin/static:/uwsgi/static
    command: /usr/bin/supervisord -c /settings/supervisord.conf
